### ISSUE TITLE
Access to the training model?

### ISSUE THREAD

**Issue by tbass134** [adblockradio/adblockradio#2]
Hello,
Just wanted to ask if there's any thought on opening sourcing on how the model was trained.  I assumed it would be in the https://github.com/adblockradio/adblockradio/tree/master/model
folder, but its empty. 
Is the training for this model proprietary?

**Comment by dest4** [comment]
Hi,
the exact model structure is contained in the public *.keras files, and you are welcome to analyze it.
The training routines and dataset are not in this code tree and are proprietary (for now).
